Minor improvements
* Match Logback for default timestamps
* NoClassDefFoundError => ClassNotFoundException when jansi is missing
* Default LogEventFormatter during JUnit tests outputs active test
* Make it simpler to use a Supplier<> for FileDestination